---
require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.7.0
  SuggestExtensions: false
  NewCops: enable
  Include:
    - ./Gemfile
    - ./Rakefile
    - '*.gemspec'
    - '**/*.rb'

Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

RSpec/FilePath:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false
